spring.application.name=studybuddy

spring.datasource.url=jdbc:postgresql://localhost:5432/studybuddydb
spring.datasource.username=eww-d
spring.datasource.password=eww-d
spring.jpa.hibernate.ddl-auto=create

# api documentation
springdoc.api-docs.path=/api
springdoc.swagger-ui.path=/swagger.html

# enable to see security filter at work
# logging.level.org.springframework.security=TRACE


# minio (file upload)
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket.name=studybuddybucket