spring.application.name=studybuddy

spring.datasource.url=jdbc:postgresql://localhost:5432/studybuddydb
spring.datasource.username=eww-d
spring.datasource.password=eww-d

# Hibernate: Schema-Generator
# schema is generated based on Entities, written to 'target/generated-schema.sql' and copied to 'schema.sql'
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=target/generated-schema.sql
spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata

# Prevent default DB generation with hibernate.
# Instead generate DB based on schema.sql and fill populate data with data.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# api documentation
springdoc.api-docs.path=/api
springdoc.swagger-ui.path=/swagger.html

# enable to see security filter at work
# logging.level.org.springframework.security=TRACE


# minio (file upload)
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket.name=studybuddybucket