DROP TABLE IF EXISTS studybuddy_user CASCADE;
DROP TABLE IF EXISTS box CASCADE;
DROP TABLE IF EXISTS box_comment CASCADE;
DROP TABLE IF EXISTS card CASCADE;
DROP TABLE IF EXISTS file_info CASCADE;

create table studybuddy_user (is_admin boolean not null, created_at timestamp(6) with time zone, id bigint generated by default as identity, last_login timestamp(6) with time zone, updated_at timestamp(6) with time zone, country varchar(255) not null, email varchar(255), firstname varchar(255) not null, foto varchar(255), gender varchar(255) not null, lastname varchar(255) not null, password varchar(255) not null, username varchar(255), primary key (id), unique (username));
create table box (is_public boolean, created_at timestamp(6) with time zone, id bigint generated by default as identity, owner_id bigint, updated_at timestamp(6) with time zone, title varchar(200) not null, description varchar(2048), primary key (id));
create table box_comment (author_id bigint, box_id bigint not null, created_at timestamp(6) with time zone, id bigint generated by default as identity, updated_at timestamp(6) with time zone, text varchar(2048) not null, primary key (id));
create table card (box_id bigint, created_at timestamp(6) with time zone, id bigint generated by default as identity, updated_at timestamp(6) with time zone, answer varchar(2000) not null, question varchar(2000) not null, media varchar(255), primary key (id));
create table file_info (created_at timestamp(6) with time zone, owner_id bigint, updated_at timestamp(6) with time zone, content_type varchar(255) not null, file_name varchar(255) not null, original_filename varchar(255) not null, primary key (file_name));

alter table if exists box add constraint FKm2ixewldssypwe5vtkuxqp706 foreign key (owner_id) references studybuddy_user;
alter table if exists box_comment add constraint FKrbokchka53stlge5jngkbkalf foreign key (author_id) references studybuddy_user;
alter table if exists box_comment add constraint FKgc3e1a4pmw03aqdogxyi96c8y foreign key (box_id) references box;
alter table if exists card add constraint FK6inmdkbve2tavgd82a3xq0lwe foreign key (box_id) references box;
alter table if exists file_info add constraint FKo78o2fu0w6cexjkfom362xxcn foreign key (owner_id) references studybuddy_user;
